ADVENTUREWORKS_OLTP:
  drivername: "mssql+pyodbc"
  user: "sa"
  password: "Rupestre.38"
  host: "localhost"
  port: "1433"
  dbname: "AdventureWorks2022"  # Asumiendo que esta es tu BD de origen
  driver: "ODBC Driver 17 for SQL Server"
  query: "?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=yes"

ADVENTUREWORKS_DW:
  drivername: "postgresql"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "datawarehouse" 

CSV_FOLDER: "./csv_data"
TRUNCATE_TABLES: true 