ADVENTUREWORKS_OLTP:
  drivername: "mssql+pyodbc"
  user: ""
  password: ""
  host: "localhost"
  port: "1433"
  dbname: ""
  driver: "ODBC Driver 17 for SQL Server"
  query: "?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=yes"

ADVENTUREWORKS_DW:
  drivername: "postgresql"
  user: ""
  password: ""
  host: "localhost"
  port: "5432"
  dbname: "datawarehouse" 

CSV_FOLDER: "./csv_data"
TRUNCATE_TABLES: true 